notifications:
  email: false
git:
  quiet: true
  depth: 1
language: java
jdk: openjdk8
python: 3
service:
- docker
addons:
  apt:
    update: true
    packages:
    - sudo
    - lsof
    - wget
    - bash
    - curl
    - jq
    - docker-ce
    - python3-dev
    - python3-pip
    - python3-six
    - python3-setuptools
install: true
before_install:
- docker-compose -v
- export PATH=$HOME/.local/bin:$PATH
- pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
- pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
- http --version --debug
- docker-compose -v
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8001 8002 8080 5432
jobs:
  include:
  - stage: test
    jdk: openjdk8
    name: integration test
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw
    - java -jar $TRAVIS_BUILD_DIR/target/*-capsule.jar &
    - wait_for 808
    - sleep 1s
    - http :8080/
    - http :8080/
    - http :8080/
    - http :8080/
    - http :8080/ololotrololo
    - http put :8080/
    - stop_any 80 8080
  - stage: test
    jdk: openjdk11
    name: versions update (openjdk11)
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
cache:
  directories:
  - ~/.docker
  - ~/.m2
  packages: true
  pip: true
